package org.robby.hbase;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cdr.proto

public final class Cdr {
    private Cdr() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }
    public interface SmCdrOrBuilder extends
            // @@protoc_insertion_point(interface_extends:SmCdr)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string dst = 1;</code>
         */
        boolean hasDst();
        /**
         * <code>required string dst = 1;</code>
         */
        java.lang.String getDst();
        /**
         * <code>required string dst = 1;</code>
         */
        com.google.protobuf.ByteString
        getDstBytes();

        /**
         * <code>required string type = 2;</code>
         */
        boolean hasType();
        /**
         * <code>required string type = 2;</code>
         */
        java.lang.String getType();
        /**
         * <code>required string type = 2;</code>
         */
        com.google.protobuf.ByteString
        getTypeBytes();

        /**
         * <code>required string dt = 3;</code>
         */
        boolean hasDt();
        /**
         * <code>required string dt = 3;</code>
         */
        java.lang.String getDt();
        /**
         * <code>required string dt = 3;</code>
         */
        com.google.protobuf.ByteString
        getDtBytes();
    }
    /**
     * Protobuf type {@code SmCdr}
     *
     * <pre>
     *package org.robby.hbase;
     * </pre>
     */
    public static final class SmCdr extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:SmCdr)
            SmCdrOrBuilder {
        // Use SmCdr.newBuilder() to construct.
        private SmCdr(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private SmCdr(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final SmCdr defaultInstance;
        public static SmCdr getDefaultInstance() {
            return defaultInstance;
        }

        public SmCdr getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private SmCdr(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            dst_ = bs;
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            type_ = bs;
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            dt_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Cdr.internal_static_SmCdr_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Cdr.internal_static_SmCdr_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Cdr.SmCdr.class, Cdr.SmCdr.Builder.class);
        }

        public static com.google.protobuf.Parser<SmCdr> PARSER =
                new com.google.protobuf.AbstractParser<SmCdr>() {
                    public SmCdr parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new SmCdr(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<SmCdr> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int DST_FIELD_NUMBER = 1;
        private java.lang.Object dst_;
        /**
         * <code>required string dst = 1;</code>
         */
        public boolean hasDst() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string dst = 1;</code>
         */
        public java.lang.String getDst() {
            java.lang.Object ref = dst_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    dst_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string dst = 1;</code>
         */
        public com.google.protobuf.ByteString
        getDstBytes() {
            java.lang.Object ref = dst_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                dst_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TYPE_FIELD_NUMBER = 2;
        private java.lang.Object type_;
        /**
         * <code>required string type = 2;</code>
         */
        public boolean hasType() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string type = 2;</code>
         */
        public java.lang.String getType() {
            java.lang.Object ref = type_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    type_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string type = 2;</code>
         */
        public com.google.protobuf.ByteString
        getTypeBytes() {
            java.lang.Object ref = type_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                type_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DT_FIELD_NUMBER = 3;
        private java.lang.Object dt_;
        /**
         * <code>required string dt = 3;</code>
         */
        public boolean hasDt() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string dt = 3;</code>
         */
        public java.lang.String getDt() {
            java.lang.Object ref = dt_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    dt_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string dt = 3;</code>
         */
        public com.google.protobuf.ByteString
        getDtBytes() {
            java.lang.Object ref = dt_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                dt_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            dst_ = "";
            type_ = "";
            dt_ = "";
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasDst()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasDt()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getDstBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getTypeBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getDtBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getDstBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getTypeBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getDtBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static Cdr.SmCdr parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Cdr.SmCdr parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Cdr.SmCdr parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Cdr.SmCdr parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Cdr.SmCdr parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static Cdr.SmCdr parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        public static Cdr.SmCdr parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        public static Cdr.SmCdr parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static Cdr.SmCdr parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static Cdr.SmCdr parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(Cdr.SmCdr prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code SmCdr}
         *
         * <pre>
         *package org.robby.hbase;
         * </pre>
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:SmCdr)
                Cdr.SmCdrOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Cdr.internal_static_SmCdr_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Cdr.internal_static_SmCdr_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Cdr.SmCdr.class, Cdr.SmCdr.Builder.class);
            }

            // Construct using Cdr.SmCdr.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }
            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                dst_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                type_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                dt_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Cdr.internal_static_SmCdr_descriptor;
            }

            public Cdr.SmCdr getDefaultInstanceForType() {
                return Cdr.SmCdr.getDefaultInstance();
            }

            public Cdr.SmCdr build() {
                Cdr.SmCdr result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Cdr.SmCdr buildPartial() {
                Cdr.SmCdr result = new Cdr.SmCdr(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.dst_ = dst_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.type_ = type_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.dt_ = dt_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Cdr.SmCdr) {
                    return mergeFrom((Cdr.SmCdr)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Cdr.SmCdr other) {
                if (other == Cdr.SmCdr.getDefaultInstance()) return this;
                if (other.hasDst()) {
                    bitField0_ |= 0x00000001;
                    dst_ = other.dst_;
                    onChanged();
                }
                if (other.hasType()) {
                    bitField0_ |= 0x00000002;
                    type_ = other.type_;
                    onChanged();
                }
                if (other.hasDt()) {
                    bitField0_ |= 0x00000004;
                    dt_ = other.dt_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasDst()) {

                    return false;
                }
                if (!hasType()) {

                    return false;
                }
                if (!hasDt()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Cdr.SmCdr parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Cdr.SmCdr) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.lang.Object dst_ = "";
            /**
             * <code>required string dst = 1;</code>
             */
            public boolean hasDst() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>required string dst = 1;</code>
             */
            public java.lang.String getDst() {
                java.lang.Object ref = dst_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        dst_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string dst = 1;</code>
             */
            public com.google.protobuf.ByteString
            getDstBytes() {
                java.lang.Object ref = dst_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    dst_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string dst = 1;</code>
             */
            public Builder setDst(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                dst_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string dst = 1;</code>
             */
            public Builder clearDst() {
                bitField0_ = (bitField0_ & ~0x00000001);
                dst_ = getDefaultInstance().getDst();
                onChanged();
                return this;
            }
            /**
             * <code>required string dst = 1;</code>
             */
            public Builder setDstBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                dst_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object type_ = "";
            /**
             * <code>required string type = 2;</code>
             */
            public boolean hasType() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            /**
             * <code>required string type = 2;</code>
             */
            public java.lang.String getType() {
                java.lang.Object ref = type_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        type_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string type = 2;</code>
             */
            public com.google.protobuf.ByteString
            getTypeBytes() {
                java.lang.Object ref = type_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    type_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string type = 2;</code>
             */
            public Builder setType(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                type_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string type = 2;</code>
             */
            public Builder clearType() {
                bitField0_ = (bitField0_ & ~0x00000002);
                type_ = getDefaultInstance().getType();
                onChanged();
                return this;
            }
            /**
             * <code>required string type = 2;</code>
             */
            public Builder setTypeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                type_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object dt_ = "";
            /**
             * <code>required string dt = 3;</code>
             */
            public boolean hasDt() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }
            /**
             * <code>required string dt = 3;</code>
             */
            public java.lang.String getDt() {
                java.lang.Object ref = dt_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        dt_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string dt = 3;</code>
             */
            public com.google.protobuf.ByteString
            getDtBytes() {
                java.lang.Object ref = dt_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    dt_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string dt = 3;</code>
             */
            public Builder setDt(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                dt_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string dt = 3;</code>
             */
            public Builder clearDt() {
                bitField0_ = (bitField0_ & ~0x00000004);
                dt_ = getDefaultInstance().getDt();
                onChanged();
                return this;
            }
            /**
             * <code>required string dt = 3;</code>
             */
            public Builder setDtBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                dt_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:SmCdr)
        }

        static {
            defaultInstance = new SmCdr(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:SmCdr)
    }

    public interface AllSmCdrOrBuilder extends
            // @@protoc_insertion_point(interface_extends:AllSmCdr)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .SmCdr cdr = 4;</code>
         */
        java.util.List<Cdr.SmCdr>
        getCdrList();
        /**
         * <code>repeated .SmCdr cdr = 4;</code>
         */
        Cdr.SmCdr getCdr(int index);
        /**
         * <code>repeated .SmCdr cdr = 4;</code>
         */
        int getCdrCount();
        /**
         * <code>repeated .SmCdr cdr = 4;</code>
         */
        java.util.List<? extends Cdr.SmCdrOrBuilder>
        getCdrOrBuilderList();
        /**
         * <code>repeated .SmCdr cdr = 4;</code>
         */
        Cdr.SmCdrOrBuilder getCdrOrBuilder(
                int index);
    }
    /**
     * Protobuf type {@code AllSmCdr}
     */
    public static final class AllSmCdr extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:AllSmCdr)
            AllSmCdrOrBuilder {
        // Use AllSmCdr.newBuilder() to construct.
        private AllSmCdr(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private AllSmCdr(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final AllSmCdr defaultInstance;
        public static AllSmCdr getDefaultInstance() {
            return defaultInstance;
        }

        public AllSmCdr getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private AllSmCdr(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 34: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                cdr_ = new java.util.ArrayList<Cdr.SmCdr>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            cdr_.add(input.readMessage(Cdr.SmCdr.PARSER, extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    cdr_ = java.util.Collections.unmodifiableList(cdr_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Cdr.internal_static_AllSmCdr_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Cdr.internal_static_AllSmCdr_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Cdr.AllSmCdr.class, Cdr.AllSmCdr.Builder.class);
        }

        public static com.google.protobuf.Parser<AllSmCdr> PARSER =
                new com.google.protobuf.AbstractParser<AllSmCdr>() {
                    public AllSmCdr parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new AllSmCdr(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<AllSmCdr> getParserForType() {
            return PARSER;
        }

        public static final int CDR_FIELD_NUMBER = 4;
        private java.util.List<Cdr.SmCdr> cdr_;
        /**
         * <code>repeated .SmCdr cdr = 4;</code>
         */
        public java.util.List<Cdr.SmCdr> getCdrList() {
            return cdr_;
        }
        /**
         * <code>repeated .SmCdr cdr = 4;</code>
         */
        public java.util.List<? extends Cdr.SmCdrOrBuilder>
        getCdrOrBuilderList() {
            return cdr_;
        }
        /**
         * <code>repeated .SmCdr cdr = 4;</code>
         */
        public int getCdrCount() {
            return cdr_.size();
        }
        /**
         * <code>repeated .SmCdr cdr = 4;</code>
         */
        public Cdr.SmCdr getCdr(int index) {
            return cdr_.get(index);
        }
        /**
         * <code>repeated .SmCdr cdr = 4;</code>
         */
        public Cdr.SmCdrOrBuilder getCdrOrBuilder(
                int index) {
            return cdr_.get(index);
        }

        private void initFields() {
            cdr_ = java.util.Collections.emptyList();
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            for (int i = 0; i < getCdrCount(); i++) {
                if (!getCdr(i).isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            for (int i = 0; i < cdr_.size(); i++) {
                output.writeMessage(4, cdr_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < cdr_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, cdr_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static Cdr.AllSmCdr parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Cdr.AllSmCdr parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Cdr.AllSmCdr parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static Cdr.AllSmCdr parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static Cdr.AllSmCdr parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static Cdr.AllSmCdr parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        public static Cdr.AllSmCdr parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        public static Cdr.AllSmCdr parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static Cdr.AllSmCdr parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static Cdr.AllSmCdr parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(Cdr.AllSmCdr prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code AllSmCdr}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:AllSmCdr)
                Cdr.AllSmCdrOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Cdr.internal_static_AllSmCdr_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Cdr.internal_static_AllSmCdr_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Cdr.AllSmCdr.class, Cdr.AllSmCdr.Builder.class);
            }

            // Construct using Cdr.AllSmCdr.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getCdrFieldBuilder();
                }
            }
            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                if (cdrBuilder_ == null) {
                    cdr_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    cdrBuilder_.clear();
                }
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Cdr.internal_static_AllSmCdr_descriptor;
            }

            public Cdr.AllSmCdr getDefaultInstanceForType() {
                return Cdr.AllSmCdr.getDefaultInstance();
            }

            public Cdr.AllSmCdr build() {
                Cdr.AllSmCdr result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Cdr.AllSmCdr buildPartial() {
                Cdr.AllSmCdr result = new Cdr.AllSmCdr(this);
                int from_bitField0_ = bitField0_;
                if (cdrBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        cdr_ = java.util.Collections.unmodifiableList(cdr_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.cdr_ = cdr_;
                } else {
                    result.cdr_ = cdrBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Cdr.AllSmCdr) {
                    return mergeFrom((Cdr.AllSmCdr)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Cdr.AllSmCdr other) {
                if (other == Cdr.AllSmCdr.getDefaultInstance()) return this;
                if (cdrBuilder_ == null) {
                    if (!other.cdr_.isEmpty()) {
                        if (cdr_.isEmpty()) {
                            cdr_ = other.cdr_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureCdrIsMutable();
                            cdr_.addAll(other.cdr_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.cdr_.isEmpty()) {
                        if (cdrBuilder_.isEmpty()) {
                            cdrBuilder_.dispose();
                            cdrBuilder_ = null;
                            cdr_ = other.cdr_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            cdrBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getCdrFieldBuilder() : null;
                        } else {
                            cdrBuilder_.addAllMessages(other.cdr_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                for (int i = 0; i < getCdrCount(); i++) {
                    if (!getCdr(i).isInitialized()) {

                        return false;
                    }
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Cdr.AllSmCdr parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Cdr.AllSmCdr) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.util.List<Cdr.SmCdr> cdr_ =
                    java.util.Collections.emptyList();
            private void ensureCdrIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    cdr_ = new java.util.ArrayList<Cdr.SmCdr>(cdr_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    Cdr.SmCdr, Cdr.SmCdr.Builder, Cdr.SmCdrOrBuilder> cdrBuilder_;

            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public java.util.List<Cdr.SmCdr> getCdrList() {
                if (cdrBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(cdr_);
                } else {
                    return cdrBuilder_.getMessageList();
                }
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public int getCdrCount() {
                if (cdrBuilder_ == null) {
                    return cdr_.size();
                } else {
                    return cdrBuilder_.getCount();
                }
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public Cdr.SmCdr getCdr(int index) {
                if (cdrBuilder_ == null) {
                    return cdr_.get(index);
                } else {
                    return cdrBuilder_.getMessage(index);
                }
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public Builder setCdr(
                    int index, Cdr.SmCdr value) {
                if (cdrBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCdrIsMutable();
                    cdr_.set(index, value);
                    onChanged();
                } else {
                    cdrBuilder_.setMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public Builder setCdr(
                    int index, Cdr.SmCdr.Builder builderForValue) {
                if (cdrBuilder_ == null) {
                    ensureCdrIsMutable();
                    cdr_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    cdrBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public Builder addCdr(Cdr.SmCdr value) {
                if (cdrBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCdrIsMutable();
                    cdr_.add(value);
                    onChanged();
                } else {
                    cdrBuilder_.addMessage(value);
                }
                return this;
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public Builder addCdr(
                    int index, Cdr.SmCdr value) {
                if (cdrBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCdrIsMutable();
                    cdr_.add(index, value);
                    onChanged();
                } else {
                    cdrBuilder_.addMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public Builder addCdr(
                    Cdr.SmCdr.Builder builderForValue) {
                if (cdrBuilder_ == null) {
                    ensureCdrIsMutable();
                    cdr_.add(builderForValue.build());
                    onChanged();
                } else {
                    cdrBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public Builder addCdr(
                    int index, Cdr.SmCdr.Builder builderForValue) {
                if (cdrBuilder_ == null) {
                    ensureCdrIsMutable();
                    cdr_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    cdrBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public Builder addAllCdr(
                    java.lang.Iterable<? extends Cdr.SmCdr> values) {
                if (cdrBuilder_ == null) {
                    ensureCdrIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, cdr_);
                    onChanged();
                } else {
                    cdrBuilder_.addAllMessages(values);
                }
                return this;
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public Builder clearCdr() {
                if (cdrBuilder_ == null) {
                    cdr_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    cdrBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public Builder removeCdr(int index) {
                if (cdrBuilder_ == null) {
                    ensureCdrIsMutable();
                    cdr_.remove(index);
                    onChanged();
                } else {
                    cdrBuilder_.remove(index);
                }
                return this;
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public Cdr.SmCdr.Builder getCdrBuilder(
                    int index) {
                return getCdrFieldBuilder().getBuilder(index);
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public Cdr.SmCdrOrBuilder getCdrOrBuilder(
                    int index) {
                if (cdrBuilder_ == null) {
                    return cdr_.get(index);  } else {
                    return cdrBuilder_.getMessageOrBuilder(index);
                }
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public java.util.List<? extends Cdr.SmCdrOrBuilder>
            getCdrOrBuilderList() {
                if (cdrBuilder_ != null) {
                    return cdrBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(cdr_);
                }
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public Cdr.SmCdr.Builder addCdrBuilder() {
                return getCdrFieldBuilder().addBuilder(
                        Cdr.SmCdr.getDefaultInstance());
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public Cdr.SmCdr.Builder addCdrBuilder(
                    int index) {
                return getCdrFieldBuilder().addBuilder(
                        index, Cdr.SmCdr.getDefaultInstance());
            }
            /**
             * <code>repeated .SmCdr cdr = 4;</code>
             */
            public java.util.List<Cdr.SmCdr.Builder>
            getCdrBuilderList() {
                return getCdrFieldBuilder().getBuilderList();
            }
            private com.google.protobuf.RepeatedFieldBuilder<
                    Cdr.SmCdr, Cdr.SmCdr.Builder, Cdr.SmCdrOrBuilder>
            getCdrFieldBuilder() {
                if (cdrBuilder_ == null) {
                    cdrBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            Cdr.SmCdr, Cdr.SmCdr.Builder, Cdr.SmCdrOrBuilder>(
                            cdr_,
                            ((bitField0_ & 0x00000001) == 0x00000001),
                            getParentForChildren(),
                            isClean());
                    cdr_ = null;
                }
                return cdrBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:AllSmCdr)
        }

        static {
            defaultInstance = new AllSmCdr(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:AllSmCdr)
    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SmCdr_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_SmCdr_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_AllSmCdr_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_AllSmCdr_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\tcdr.proto\".\n\005SmCdr\022\013\n\003dst\030\001 \002(\t\022\014\n\004typ" +
                        "e\030\002 \002(\t\022\n\n\002dt\030\003 \002(\t\"\037\n\010AllSmCdr\022\023\n\003cdr\030\004" +
                        " \003(\0132\006.SmCdr"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_SmCdr_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_SmCdr_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_SmCdr_descriptor,
                new java.lang.String[] { "Dst", "Type", "Dt", });
        internal_static_AllSmCdr_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_AllSmCdr_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_AllSmCdr_descriptor,
                new java.lang.String[] { "Cdr", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
